### Add Flight V2
POST http://localhost:4004/odata/v2/flightSet/Flights
Content-Type: application/json

{ "carrID":"AA", 
  "connID":"0123",
  "fldate":"2022-03-30T12:00:00Z"
}

### Get All Flights
GET http://localhost:4004/flightSet/Flights

### Get A single flight v2
GET http://localhost:4004/odata/v2/flightSet/Flights(carrID='AZ',connID='0788',fldate=2022-04-30T22%3A00%3A00Z)

### Get All Games v2
GET http://localhost:4004/odata/v2/gameSet/Games
